services:
  backend:
    image: ghcr.io/ksperis/s3-manager-backend:${S3_MANAGER_TAG:-latest}
    env_file:
      - backend/.env.example
    environment:
      CORS_ORIGINS: '["http://localhost:8080"]'
      DATABASE_URL: sqlite:////data/app.db
      APP_SETTINGS_PATH: /data/app_settings.json
    volumes:
      - backend-data:/data
    ports:
      - "8000:8000"
  frontend:
    image: ghcr.io/ksperis/s3-manager-frontend:${S3_MANAGER_TAG:-latest}
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      NGINX_CONF: compose

volumes:
  backend-data:
