[pytest]
filterwarnings =
    ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning:passlib\.utils
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx\._client
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:requests_aws4auth\.aws4signingkey
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:requests_aws4auth\.aws4auth
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:jose\.jwt
