apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-manager.fullname" . }}-backend
  labels:
    {{- include "s3-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: http
