apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-manager.fullname" . }}-frontend
  labels:
    {{- include "s3-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: http
