{{- if .Values.postgresql.enabled }}
{{- $name := include "s3-manager.fullname" . -}}
{{- $host := printf "%s-postgresql" $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-postgresql
  labels:
    {{- include "s3-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password $host .Values.postgresql.service.port .Values.postgresql.auth.database | quote }}
{{- end }}
