"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-01-27 18:35:03.450645
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.core.security import EncryptedString


revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_login_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('code_verifier', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('redirect_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    with op.batch_alter_table('oidc_login_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_login_states_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oidc_login_states_state'), ['state'], unique=False)

    op.create_table('s3_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('access_key_enc', sa.String(), nullable=False),
    sa.Column('secret_key_enc', sa.String(), nullable=False),
    sa.Column('access_key_hash', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('can_manage_iam', sa.Boolean(), nullable=False),
    sa.Column('can_manage_buckets', sa.Boolean(), nullable=False),
    sa.Column('can_view_traffic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('s3_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_s3_sessions_access_key_hash'), ['access_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_s3_sessions_id'), ['id'], unique=False)

    op.create_table('storage_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('admin_endpoint', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('admin_access_key', sa.String(), nullable=True),
    sa.Column('admin_secret_key', EncryptedString(), nullable=True),
    sa.Column('supervision_access_key', sa.String(), nullable=True),
    sa.Column('supervision_secret_key', EncryptedString(), nullable=True),
    sa.Column('features_config', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_editable', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_url', name='uq_storage_endpoints_endpoint'),
    sa.UniqueConstraint('name', name='uq_storage_endpoints_name')
    )
    with op.batch_alter_table('storage_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_endpoints_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_root', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('auth_provider_subject', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'auth_provider_subject', name='uq_users_provider_subject'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('s3_session_id', sa.String(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['s3_session_id'], ['s3_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_s3_session_id'), ['s3_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('s3_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rgw_account_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('rgw_access_key', sa.String(), nullable=True),
    sa.Column('rgw_secret_key', EncryptedString(), nullable=True),
    sa.Column('rgw_user_uid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('storage_endpoint_id', sa.Integer(), nullable=True),
    sa.Column('portal_settings_override', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['storage_endpoint_id'], ['storage_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rgw_account_id')
    )
    with op.batch_alter_table('s3_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_s3_accounts_id'), ['id'], unique=False)

    op.create_table('s3_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('storage_endpoint_id', sa.Integer(), nullable=True),
    sa.Column('custom_endpoint_config', sa.Text(), nullable=True),
    sa.Column('access_key_id', sa.String(), nullable=False),
    sa.Column('secret_access_key', EncryptedString(), nullable=False),
    sa.Column('session_token', EncryptedString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storage_endpoint_id'], ['storage_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_s3_connections_owner_name')
    )
    with op.batch_alter_table('s3_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_s3_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_s3_connections_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_s3_connections_storage_endpoint_id'), ['storage_endpoint_id'], unique=False)

    op.create_table('s3_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rgw_user_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('rgw_access_key', sa.String(), nullable=False),
    sa.Column('rgw_secret_key', EncryptedString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('storage_endpoint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['storage_endpoint_id'], ['storage_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rgw_user_uid', name='uq_s3_users_uid')
    )
    with op.batch_alter_table('s3_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_s3_users_id'), ['id'], unique=False)

    op.create_table('account_iam_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('iam_user_id', sa.String(), nullable=False),
    sa.Column('iam_username', sa.String(), nullable=True),
    sa.Column('active_access_key', sa.String(), nullable=True),
    sa.Column('active_secret_key', EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['s3_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iam_user_id', name='uq_account_iam_user_id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_account_iam_user')
    )
    with op.batch_alter_table('account_iam_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_iam_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['s3_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('user_s3_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_root', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('account_role', sa.String(), nullable=False),
    sa.Column('account_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_manage_iam', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_manage_buckets', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('can_manage_portal_users', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_view_root_key', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['s3_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_user_s3_account')
    )
    with op.batch_alter_table('user_s3_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_s3_accounts_id'), ['id'], unique=False)

    op.create_table('user_s3_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_connection_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['s3_connection_id'], ['s3_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 's3_connection_id', name='uq_user_s3_connection')
    )
    with op.batch_alter_table('user_s3_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_s3_connections_id'), ['id'], unique=False)

    op.create_table('user_s3_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s3_user_id'], ['s3_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 's3_user_id', name='uq_user_s3_user')
    )
    with op.batch_alter_table('user_s3_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_s3_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_s3_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_s3_users_id'))

    op.drop_table('user_s3_users')
    with op.batch_alter_table('user_s3_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_s3_connections_id'))

    op.drop_table('user_s3_connections')
    with op.batch_alter_table('user_s3_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_s3_accounts_id'))

    op.drop_table('user_s3_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('account_iam_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_iam_users_id'))

    op.drop_table('account_iam_users')
    with op.batch_alter_table('s3_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_s3_users_id'))

    op.drop_table('s3_users')
    with op.batch_alter_table('s3_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_s3_connections_storage_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_s3_connections_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_s3_connections_id'))

    op.drop_table('s3_connections')
    with op.batch_alter_table('s3_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_s3_accounts_id'))

    op.drop_table('s3_accounts')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_s3_session_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_id'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('storage_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_endpoints_id'))

    op.drop_table('storage_endpoints')
    with op.batch_alter_table('s3_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_s3_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_s3_sessions_access_key_hash'))

    op.drop_table('s3_sessions')
    with op.batch_alter_table('oidc_login_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_login_states_state'))
        batch_op.drop_index(batch_op.f('ix_oidc_login_states_created_at'))

    op.drop_table('oidc_login_states')
    # ### end Alembic commands ###
